version: '3.1'

services:
  nginx:
    image: nginx
    # restart: always
    # hostname: zoo1
    ports:
      - 80
    # environment:
    #   ZOO_MY_ID: 1
    #   ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - /home/jack/docker-test/sharedata:/mnt/sharedata
      - ./default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:fpm
    # restart: always
    # hostname: zoo2
    # ports:
    #   - 2182:2181
    # environment:
    #   ZOO_MY_ID: 2
    #   ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - /home/jack/docker-test/sharedata:/mnt/sharedata
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker-php-ext-sodium.ini:/usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
      - ./extensions/redis.so:/usr/local/lib/php/extensions/no-debug-non-zts-20190902/redis.so
      - ./scripts:/var/www/html/scripts

  mysql:
    image: mysql
    # restart: always
    # hostname: zoo2
    # ports:
    #   - 2182:2181
    environment:
      MYSQL_ROOT_PASSWORD: 111111
    #   ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - /home/jack/docker-test/sharedata:/mnt/sharedata

  redis:
    image: redis
    volumes:
      - /home/jack/docker-test/sharedata:/mnt/sharedata
      

