version: '3.1'

services:
  resty:
    image: openresty/openresty
    # restart: always
    hostname: resty2
    ports:
      - 8081:80
    environment:
        TZ : 'Asia/Shanghai'
    # environment:
    #   ZOO_MY_ID: 1
    #   ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - /home/jack/docker-test/sharedata/lua:/usr/local/openresty/nginx/ttt
      - /home/jack/gitroot/new_mini/miniw_activity/env1/lua:/usr/local/openresty/nginx/lua
      - /home/jack/gitroot/setting/docker/resty/default.conf:/etc/nginx/conf.d/default.conf
      - /home/jack/gitroot/setting/docker/resty/logs:/usr/local/openresty/nginx/logs

    working_dir: /usr/local/openresty/nginx
    command:
      [sbin/nginx, '-p', '/usr/local/openresty/nginx', '-g', 'daemon off;']
