apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: openresty
    name: openresty
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: openresty
    type: NodePort
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: openresty2
    name: openresty2
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: openresty2
    type: NodePort
  status:
    loadBalancer: {}

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: openresty
    name: openresty
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: openresty
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: openresty
      spec:
        containers:
        - image: openresty/openresty
          imagePullPolicy: IfNotPresent
          name: openresty
          resources: {}
  status: {}
    
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: openresty2
    name: openresty2
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: openresty2
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: openresty2
      spec:
        containers:
        - image: openresty/openresty
          imagePullPolicy: IfNotPresent
          name: openresty2
          resources: {}
  status: {}
