apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: openresty
  name: openresty
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: openresty
  type: NodePort
status:
  loadBalancer: {}
