apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: openresty2
  name: openresty2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: openresty2
  type: NodePort
status:
  loadBalancer: {}
  
