(deftheme my-theme-true-color
  "Created 2018-01-20.")

(custom-theme-set-faces
 'my-theme-true-color
 '(default ((t (:family "default" :foundry "default" :width normal :height 1 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#b2b2b2" :background "#292b2e" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#e3dedd"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:family "Arial" :foundry "outline")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#4f97d7" :inherit (bold)))))
 '(highlight ((t (:foreground "#b2b2b2" :background "#444155"))))
 '(region ((t (:background "#444155"))))
 '(shadow ((t (:foreground "#686868"))))
 '(secondary-selection ((t (:background "#100a14"))))
 '(trailing-whitespace ((t (:background "#e0211d"))))
 '(font-lock-builtin-face ((t (:foreground "#4f97d7"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:slant normal :foreground "#2aa1ae" :background "#292e34"))))
 '(font-lock-constant-face ((t (:foreground "#a45bad"))))
 '(font-lock-doc-face ((t (:foreground "#9f8766"))))
 '(font-lock-function-name-face ((t (:foreground "#bc6ec5" :inherit (bold)))))
 '(font-lock-keyword-face ((t (:foreground "#4f97d7" :inherit (bold)))))
 '(font-lock-negation-char-face ((t (:foreground "#a45bad"))))
 '(font-lock-preprocessor-face ((t (:foreground "#bc6ec5"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#2d9574"))))
 '(font-lock-type-face ((t (:foreground "#ce537a" :inherit (bold)))))
 '(font-lock-variable-name-face ((t (:foreground "#7590db"))))
 '(font-lock-warning-face ((t (:foreground "#dc752f" :background "#292b2e"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#2aa1ae"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#c56ec3"))))
 '(fringe ((t (:foreground "#b2b2b2" :background "#292b2e"))))
 '(header-line ((t (:background "#0a0814"))))
 '(tooltip ((t (:weight normal :slant normal :underline nil :foreground "#b2b2b2" :background "#5e5079"))))
 '(mode-line-buffer-id ((t (:foreground "#bc6ec5" :inherit (bold)))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line          ((t (:box (:line-width 1 :color "#b3b9be" :style nil) :foreground "#2d2d40" :background "#d7dfff"))))
 '(mode-line-inactive ((t (:foreground "#5f5f87" :background "#d7dfff"))))
 '(isearch ((t (:foreground "#292b2e" :background "#86dc2f"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:weight normal :background "#29422d"))))
 '(match ((t (:foreground "#86dc2f" :background "#444155"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'my-theme-true-color)
